### ISSUE TITLE
warn on "(void)" in XSUB arglist

### ISSUE THREAD

**Issue by amba** [benkasminbullock/xs-check#1]
I recently got this wrong in the USB::LibUSB XS:

```
int
test_arglist(void)
CODE:
    RETVAL = 1;
OUTPUT:
    RETVAL
```
vs.

```
int
test_arglist()
CODE:
    RETVAL = 1;
OUTPUT:
    RETVAL
```

The former will produce a "Usage: Test::Arglist::test_arglist(void)" error at runtime. But in C it is good style to use (void) instead of ().
Is it possible to add a warning for this?

**Comment by benkasminbullock** [comment]
That seems reasonable. I've added another test for that.

Please try version 0.06 on CPAN now and let me know if that works for you.

**Comment by amba** [comment]
Yeah it seems to work fine. But why do you also check normal C functions? This way you also get a warnings for the following valid XS code:

```
#define PERL_NO_GET_CONTEXT
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"

#include "const-c.inc"


static int
return_one(void)
{
    return 1;
}

MODULE = Test::Arglist		PACKAGE = Test::Arglist		

INCLUDE: const-xs.inc

int
test_arglist()
CODE:
    RETVAL = return_one();
OUTPUT:
    RETVAL
```

**Comment by benkasminbullock** [comment]
I've removed that from the module in d7afed8865024770b244b5b6a34840d51db276cf

Since the basic problem seems to be fixed, I'm closing the issue. Please open it again if you're not satisfied. Thank you for the report.
