### ISSUE TITLE
RFE: Discourage use of SvPV

### ISSUE THREAD

**Issue by FGasper** [benkasminbullock/xs-check#3]
SvPV is problematic because it’s basically bytes.pm for C: it leaks Perl’s internals to external C code. SvPVbyte and SvPVutf8 are often preferable.

I recently [updated Perl’s documentation](https://github.com/Perl/perl5/commit/3c3f883d1ac1fc6048277d2d60015c66c211ac9b) to reflect this; it would be nice if this module followed suit.

Thank you!

**Comment by benkasminbullock** [comment]
I'll think about how to do this.

**Comment by benkasminbullock** [comment]
Some work here:
81add8ded35c7498707d89b98d9ba8bf31cb9013

**Comment by benkasminbullock** [comment]
@FGasper - is that about what you were thinking about?

**Comment by FGasper** [comment]
Basically. There are other variants, too, like SvPV_nolen … I’ll see if I can come up with a definitive list of recommended alternatives.

**Comment by FGasper** [comment]
SvPV -> SvPVbyte or SvPVutf8
SvPV_nolen -> SvPVbyte_nolen or SvPVut8_nolen
SvPV_force -> SvPVbyte_force or SvPVutf8_force
SvPVx -> SvPVbytex or SvPVutf8x

**Comment by benkasminbullock** [comment]
This should be OK: 4c2c2c7d5736d770b82fae25d6bbd2d258017a37

**Comment by benkasminbullock** [comment]
I want to release this to CPAN and close the issue, I understand the module is hard to install from the github repository, but can you take a look at the current commit particularly this file: https://github.com/benkasminbullock/xs-check/blob/master/t/svpv.t and let me know if that is OK? Thanks.

**Comment by benkasminbullock** [comment]
I'm just going to push ahead with this but you can open this issue again if you're not satisfied.

The module is up on CPAN as

https://metacpan.org/release/BKB/XS-Check-0.12

Thank you for the bug report and suggestion. Please let me know if you have any other ideas.

By the way the module has four stars on CPAN but I'm not actually sure anyone is actually using it, so this may all be academic.
